- hosts: proxmoxNAS
  tasks: 
    - ansible.builtin.include_role:
      name: proxmox
      tasks_from: installingNFSContainer.yml
      vars:
        nic: "nicWired"
        containerIPGateway: "10.10.10.1"
        containerIp: "10.10.10.5"
        bridge: "vmbr0"
        proxmoxMountPoint: "/mnt/nfs/{{ ansible_hostname }}/export/"
        containerMountPoint: /export/

  
- hosts: NFSNASContainer
  roles:
    - NFSServer