cisco:
    hosts:
        SwCore1:
        SwCore2:
        SwEdge1:
        ciscoRouter:
    vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_pass: "{{ numberPasswordStrong }}"

routers:
    hosts:
        ciscoRouter:
            ansible_host: 10.3.1.1

        juniperRouter:
            ansible_host: 10.2.1.1 
            ansible_password: "{{ textPassword }}"
    vars:
        vrrpVirtualIp: 10.5.5.1



switches:
    hosts:
        SwCore1:
            ansible_host: 10.5.5.4
        SwCore2:
            ansible_host: 10.5.5.5
        SwEdge1:
            ansible_host: 10.5.5.6
    vars:
        defGateway: 10.5.5.1


firewalls:
    hosts:
        opnsense:
            ansible_host: 10.2.1.3

servers:
    hosts:
        proxmox:
            ansible_host: 10.2.1.2
            ansible_user: root
        adminNode:
            ansible_host: 10.100.100.2
        internalNetworkServer:
            ansible_host: 10.10.10.5
        externalNetworkServer:
            ansible_host: 10.50.50.5


networking:
    children:
        routers:
        switches:
        firewalls:
    vars:
        ansible_user: miguel
        ansible_password: "{{ numberPasswordStrong }}"
        newUser: ansible
        