


routers:
    hosts:
        ciscoRouter:
            ansible_host: 10.3.1.1

        juniperRouter:
            ansible_host: 10.2.1.1 
        



switches:
    hosts:
        SwCore1:
            ansible_host: 10.5.5.4
        SwCore2:
            ansible_host: 10.5.5.5
        SwEdge1:
            ansible_host: 10.5.5.6
    vars:
        defGateway: 10.5.5.1


firewalls:
    hosts:
        opnsense:
            ansible_host: 10.2.1.3

servers:
    hosts:
        proxmoxAdmin:
            ansible_host: 10.2.1.2
            ansible_user: root
        adminNode:
            ansible_host: 10.2.1.4
            ansible_user: miguel
        proxmoxNAS:
            ansible_host: 10.10.10.2
            ansible_user: root
        NFSNASContainer:
            ansible_host: 10.10.10.5
            ansible_user: root
        externalNetworkServer:
            ansible_host: 10.50.50.5
            


networking:
    children:
        routers:
        switches:
        firewalls:
        


cisco:
    hosts:
        SwCore1:
        SwCore2:
        SwEdge1:
        ciscoRouter: